"""Architect Agent module for VibeDev.

This module provides the schema and prompts for the Architect Agent,
which is responsible for designing execution plans (workflows) based on user goals.
"""

from __future__ import annotations

from typing import Any, Literal
from pydantic import BaseModel, Field


class WorkflowNode(BaseModel):
    """A single step in a generated workflow."""
    
    id: str = Field(..., description="Unique identifier for the step (e.g., 'step-1')")
    title: str = Field(..., description="Concise title of the step")
    description: str = Field(..., description="Detailed description of what needs to be done")
    type: Literal["code_modification", "verification", "research", "manual_review"] = Field(
        ..., description="Type of activity in this step"
    )
    dependencies: list[str] = Field(
        default_factory=list,
        description="IDs of steps that must completions before this one starts"
    )
    acceptance_criteria: list[str] = Field(
        default_factory=list,
        description="Specific conditions that must be met for this step to be considered complete"
    )
    required_evidence: list[str] = Field(
        default_factory=list,
        description="List of evidence types required (e.g., 'tests_passed', 'screenshot')"
    )


class WorkflowTemplate(BaseModel):
    """A full workflow template generated by the Architect."""
    
    title: str = Field(..., description="Title of the workflow")
    description: str = Field(..., description="High-level description of the strategy")
    nodes: list[WorkflowNode] = Field(..., description="List of steps in the workflow")
    rationale: str = Field(..., description="Explanation of why this plan was chosen")


ARCHITECT_SYSTEM_PROMPT = """You are the Architect Agent for VibeDev.
Your goal is to design robust, step-by-step execution plans (workflows) for software development tasks.

Rules for planning:
1. Break down complex tasks into small, verifiable steps.
2. Ensure each step has clear acceptance criteria.
3. Use 'verification' steps to explicitly check for regressions or correctness.
4. For features involving UI, include steps to verify the visual appearance.
5. Create dependencies to ensure a logical flow.
6. If the user's goal is vague, include a 'research' step first.

Return your response as a strictly valid JSON object adhering to the WorkflowTemplate schema.
"""


def convert_template_to_steps(template: WorkflowTemplate) -> list[dict[str, Any]]:
    """Convert an Architect WorkflowTemplate to VibeDev store steps."""
    steps = []
    
    # Simple topological sort could happen here, or we just trust the order
    # For now, we linearize based on dependencies or list order
    
    for i, node in enumerate(template.nodes):
        step = {
            "title": node.title,
            "instruction_prompt": f"{node.description}\n\nRationale: {template.rationale}",
            "acceptance_criteria": node.acceptance_criteria,
            "required_evidence": node.required_evidence,
            "gates": [],  # Architect could define gates too, but for now empty
            "step_id": node.id,
        }
        
        # Map node types to standard gates/evidence
        if node.type == "verification":
            step["required_evidence"].extend(["tests_passed", "tests_run"])
            step["gates"].append({
                "type": "tests_passed",
                "description": "Verification tests must pass"
            })
            
        elif node.type == "manual_review":
             step["gates"].append({
                "type": "human_approval",
                "description": "Manual review required"
            })
            
        steps.append(step)
        
    return steps
